[package]

# Semantic Versioning is used: https://semver.org/
version = "4.0.0"

# Description
category = "isaaclab"
readme  = "README.md"

title = "Quadruped Tasks Extension"
author = "Felipe Mohr"
maintainer = "Felipe Mohr"
description="Quadruped Tasks Extension for Isaac Lab"
repository = "https://github.com/felipemohr/IsaacLab-Quadruped-Tasks.git"
keywords = ["locomotion", "quadruped", "isaaclab"]

[dependencies]
"omni.isaac.lab" = {}
"omni.isaac.lab_assets" = {}
"omni.isaac.lab_tasks" = {}
# NOTE: Add additional dependencies here

[[python.module]]
name = "omni.isaac.lab_quadruped_tasks"

[isaaclab_settings]
# TODO: Uncomment and list any apt dependencies here.
#       If none, leave it commented out.
# apt_deps = ["example_package"]
# TODO: Uncomment and provide path to a ros_ws
#       with rosdeps to be installed. If none,
#       leave it commented out.
# ros_ws = "path/from/extension_root/to/ros_ws"
